export interface OrderDetail {
    orderDetailID?: string
    orderID?: string
    productID?: string
    productCode?: string
    productName?: string
    quantityOrg?: number
    quantity?: number
    quantityBefore?: number
    price?: number
    amount?: number
    discountPercent?: number
    discountAmount?: number
    taxPercent?: number
    taxAmount?: number
    totalAmount?: number
    sortOrder?: number
    barcode?: string
    taxID?: number
    unitID?: string
    unitName?: string
    notes?: any
    blockUnit?: any
    blockUnitName?: any
    quantityOnBlock?: number
    unitNotes?: any
    productCategoryListID?: string
    isSaleOrder?: boolean
    quantityInventoryApproval?: number
    isPromotion?: boolean
    promotionType?: any
    promotionID?: any
    quantityBuy?: number
    transactionCode?: any
    produceStatus?: number
    searchString?: string
    lotCode?: any
    expiryDate?: any
    isExpiryDate?: boolean
    expiryDateString?: string
    balanceQuantity?: number
    orderQuantity?: number
    promotionNotes?: any
    stockNotes?: any
    localName?: string
    isReScale?: boolean
    quantityProduce?: number
    purchaseLastPrice?: number
    itemType?: number
    isOutOfStock?: boolean
    isApproved?: boolean
}  